name: Build

on:
  push:
    branches:
      - main

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macOS-11]

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.14.1
        with:
          output-dir: dist
  
      - uses: actions/upload-artifact@v3
        with:
          name: python-package-distributions
          path: ./dist/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3

      - name: Create source distribution
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v3
        with:
          name: python-package-distributions
          path: ./dist/*.tar.gz

  audit_abi3_wheels:
    name: Audit ABI3 wheels
    runs-on: ubuntu-latest
    needs:
      - build_wheels

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: python-package-distributions
          path: ./dist/
      - uses: actions/setup-python@v3
      - run: pipx run abi3audit dist/*abi3*.whl

  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs:
      - build_wheels
      - build_sdist
      - audit_abi3_wheels

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: python-package-distributions
          path: ./dist/

      - name: Publish source distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip_existing: true # This should be removed for v0.2.4
